name: ✨Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for taking the time to submit a feature request! Before submitting, please review the guidelines and provide as much detail as possible.

        ### Guidelines

        1. **Search**: Before submitting a feature request, please search through other open/closed issues to ensure that a similar request hasn't already been made.

        2. **Clarity**: Provide a clear and concise description of the feature or enhancement you would like. Explain what the feature should do and why it would be beneficial.

        3. **Use Cases**: Describe the specific use cases or scenarios where this feature would be useful. Provide examples or anecdotes to illustrate its value.

        4. **Proposed Solution**: If you have any ideas or suggestions for how the feature could be implemented, please share them. This could include technical details, architectural considerations, or design mockups.

        5. **Impact**: Explain how this feature would impact users, the project, or the community. Discuss potential benefits and any potential drawbacks or trade-offs.

        6. **Additional Information**: Provide any additional information that might be helpful in understanding and implementing the feature. This could include related links, references, screenshots, or any other relevant resources.

        Your cooperation in following these guidelines is greatly appreciated!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe the specific use cases or scenarios where this feature would be useful
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Share any ideas or suggestions for how the feature could be implemented
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Explain how this feature would impact users, the project, or the community
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information that might be helpful in understanding and implementing the feature

